batch_size: 1024
height: 32
learning_rate: 0.0001
max_text_length: 23
model_path: /opt/text_recognition/01_image_to_word/models/202304090507
train_epochs: 100
train_workers: 20
vocab: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
width: 128
